### ISSUE TITLE
[Feature Request] Hexadecimal formatting with :x and :X

### ISSUE THREAD

**Issue by VelocityRa** [iwt-svenulrich/typescript-string-operations#18]
As supported by standard `printf` implementations.

**Comment by iwt-svenulrich** [comment]
Hi @VelocityRa 

im currently looking at this Feature in C and found out that negatives are handled different than i would expect. See this post on Stackoverflow. https://stackoverflow.com/questions/30378633/c-printing-negative-int-values-as-hex-produces-too-many-characters

Im going to implement that feature the "simple" way, which would return the output simply with the minus in front.

**Comment by iwt-svenulrich** [comment]
implemented with version 1.4.0

**Comment by VelocityRa** [comment]
That was fast :) 👍
